### ISSUE TITLE
Strange permission problem

### ISSUE THREAD

**Issue by criwe** [IchHabRecht/TYPO3-multicolumn#2]
Hi!

I´ve discovered a strange behavior. A site has some content elementes:

content A
multicolumn
content B

When I want to edit "content B" via pagemodul, using the pensil-icon -> an error occurs "Sorry, you 
didn't have proper permissions to perform this change." (its an admin-account!!)

![screen](https://cloud.githubusercontent.com/assets/7531138/4385524/a12b7c2c-43c5-11e4-8fc5-29200243ca23.jpg)

When I move "content B"  above the multicolumn-element, everything works fine?!

TYPO3 6.2.4

Best regards
Chris

**Comment by IchHabRecht** [comment]
Sorry for the very delayed answer. I have tested your issue with TYPO3 6.2.25 and multicolumn 2.2.1 but can't verify the problem. Have you found any solution or can you provide more information about the system?

**Comment by criwe** [comment]
Np! I´ve looked in the system i think the problem occured, but seemed to work fine now. Can be closed! :-)

**Comment by IchHabRecht** [comment]
Thanks for your response!
