### ISSUE TITLE
INVALID VALUE when creating new multicolumn content element with custom layout

### ISSUE THREAD

**Issue by jousch** [IchHabRecht/TYPO3-multicolumn#20]
_ext:github-master
TYPO3: 7.6.10_

---
# Problem
Only the default flexform selectbox options for `preSetLayout` are available when an editor tries to creating a new multicolumn CE (independently if he creates one with the new content element wizard link item): `(INVALID VALUE ("readMore.")`. Interesting is, that all default options are displayed, although they are disabled via pageTSConfig as you can see later.

# Workaround
Save content element once to get all (per pageTSConfig configured) <option>'s for the flexform field `preSetLayout`

# Actual conditions
## Actual configuration for ext:multicolumn (pageTSConfig)
```
tx_multicolumn {
	config {
		layoutPreset {
				// enable only readMore container layout
			enableLayouts = readMore
		}
	}

		// create readMore container
	layoutPreset {
		readMore {
			label = LLL:EXT:themepackagefoobar/Resources/Private/Language/locallang_be.xml:multicolumn.readMore.label
			icon = EXT:themepackagefoobar/Resources/Public/Images/Backend/multicolumnReadMore.gif
			config {
				columns = 1
			}
		}
	}
}
```
# My thoughts
Seems like the configuration for available `preSetLayout` must be adopted to work with TYPO3 7.6? (Before upgrading the TYPO3 instance, it was a TYPO3 4.5). Actually `tx_multicolumn.config.layoutPreset.enableLayouts` is considered only after save and subsequently page reload.

# How to fix
Do you have some ideas, how I can fix this? Or an hint, where I should begin to debug?

Cheers,
Josef

**Comment by IchHabRecht** [comment]
Have you really tried the current master (3.10) release? This should be fixed with commit https://github.com/IchHabRecht/TYPO3-multicolumn/commit/9cd62785d02aca259d1314132ffa49d73c16e88a

**Comment by jousch** [comment]
Thx! Fixed!
