### ISSUE TITLE
LLL:EXT:cms/locallang_tca.xml:pages.tabs.access does not work in 7.6 anymore

### ISSUE THREAD

**Issue by Diologenes** [IchHabRecht/TYPO3-multicolumn#24]
Hey Nicole, 

just a small issue in TYPO3 7.6. The translation for the access-tab does not appear.

Could you please replace 
`LLL:EXT:cms/locallang_tca.xml:pages.tabs.access`
with
`LLL:EXT:cms/locallang_tca.xlf:pages.tabs.access`

in Configuration/TCA/Overrides/tt_content.php.

Thank you! ;-)

**Comment by IchHabRecht** [comment]
Hi Gerald,

Thanks for your feedback. The label you are referring to is taken from the current TCA and not modified in any way by the export extension. Can you please check your current TCA within your export installation.

**Comment by IchHabRecht** [comment]
Sorry, I mixed up extensions. Will have another look here.
